name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the master branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Store Docker Hub credentials in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t hasan2407/express-ts-aws:latest .
          
      - name: Push Docker image to Docker Hub
        run: |
          docker push hasan2407/express-ts-aws:latest
          
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job runs before deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to EC2 and run deployment script
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull hasan2407/express-ts-aws:latest
            docker stop express-ts-container || true  # Stop the old container if it exists
            docker rm express-ts-container || true  # Remove the old container if it exists
            docker run -d -p 5000:5000 --name express-ts-container hasan2407/express-ts-aws:latest
